/**
 * Represents a clickable choice that the player can interact with during an event.
 * @typedef DialogueOption
 * @property {int} OptionIndex index within the option doc
 * @property {String} Text the actual text of the option
 * @property {int} AffectionChange
 *  @property {int} Destination or which script object it sends you to when clicked
 */

/**
 * Represents the main dialogue spoken to the player during an event.
 * @typedef ScriptObject
 *@property {int} Index index within the normal dialogue doc
 * @property {String} CharacterState facial expresssion of the character
 * @property {string} Text text of the interaction
 *@property {DialogueOption[]} Options Included choices the player can make
 *@property {String} Background The background selection for the scene
 */

const IntroSegment = [
  [
    {
      Index: 0,
      CharacterState: "Empty",
      Text: "I can’t believe this! Is it really the career fair already? I barely got my resume together in time last night, I’m totally unprepared!",
      Background: "Room",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "Empty",
      Text: "Shoot, it’s already almost noon! I need to get going soon or I’m dead meat!",
      Background: "Room",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "Empty",
      Text: "I made it in time! But barely! Gotta get to the tech section quick! But where is it?",
      Background: "Conference",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "Go Left", Destination: 19, AffectionChange: 0.0 },
        { OptionIndex: 1.0, Text: "Go Right", Destination: 1, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 1,
      CharacterState: "Empty",
      Text: "Hm, this looks right... there's only 4 tables though. I hoped there'd be more than this... I guess I'll start from the close end.",
      Background: "Corridor",
      Destination: -1,
      Options: [
        {
          OptionIndex: 2.0,
          Text: "Visit the table with the model rocket",
          Destination: 2,
          AffectionChange: 0.0,
        },
      ],
    },
    {
      Index: 2,
      CharacterState: "MartinNeut",
      Text: "Howdy there! Are you here for the career fair? My name is Martin L. Ray, but you can just call me Marty!",
      Background: "Table",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "MartinMyst",
      Text: "My company Raylock specializes in the development of new technology, for the sake of protecting our dear home nation, Web.Landia!",
      Background: "Table",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "MartinIbuk",
      Text: "Here's the number for later. So whaddya say, are you interested?",
      Background: "Table",
      Destination: -1,
      Options: [
        { OptionIndex: 3.0, Text: "Yeah, of course!", Destination: 5, AffectionChange: 0.0 },
        {
          OptionIndex: 5.0,
          Text: "Sorry, could you repeat that? I was too busy staring into your eyes...",
          Destination: 5,
          AffectionChange: 0.0,
        },
      ],
    },
    {
      Index: 5,
      CharacterState: "MartinFlus",
      Text: "It was nice talking to you, but I you should probably move on! Wouldn't want to keep the others waiting, after all.",
      Background: "Table",
      Destination: 6,
    },
    {
      Index: 6,
      CharacterState: "EdnaNeut",
      Text: "Hello, my name is Edna Tonne, and I am a Junior Researcher at the Ungulate Institute of Technology.",
      Background: "Table",
      Destination: 7,
    },
    {
      Index: 7,
      CharacterState: "EdnaNeut",
      Text: "My lab here studies the depths of advanced computer science. Our work isn't easy; you really have to know what you're doing to get far in this field.",
      Background: "Table",
      Destination: 8,
    },
    {
      Index: 8,
      CharacterState: "EdnaHappy",
      Text: "We happen to be looking for new assistants. I think you have potential.. Take a card, won't you?",
      Background: "Table",
      Destination: -1,
      Options: [
        { OptionIndex: 9.0, Text: "I'll be in touch!", Destination: 9, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 9,
      CharacterState: "EdnaNeut",
      Text: "Why don't you move along now?  It's almost lunchtime.",
      Background: "Table",
      Destination: 10,
    },
    {
      Index: 10,
      CharacterState: "JpRizz",
      Text: "Hey kid, how're doing? Good? Good. I'm doing good too. My name is JP Silverbags, by the way, and I'm a consultant for the Castle Avenue Bank. ",
      Background: "Table",
      Destination: 11,
    },
    {
      Index: 11,
      CharacterState: "JpNeut",
      Text: 'We have a motto here:  "avarice is awesome". You know the right people, push the right buttons, you can go far.',
      Background: "Table",
      Destination: 12,
    },
    {
      Index: 12,
      CharacterState: "JpNeut",
      Text: "You might not look like much now, but I think you'll be worth something. Have this. On me.",
      Background: "Table",
      Destination: -1,
      Options: [
        {
          OptionIndex: 10.0,
          Text: '"Avarice is awesome," huh. ',
          Destination: 13,
          AffectionChange: 0.0,
        },
        {
          OptionIndex: 11.0,
          Text: "Avarice is awesome, and so are you!",
          Destination: 13,
          AffectionChange: 0.0,
        },
      ],
    },
    {
      Index: 13,
      CharacterState: "JpAgit",
      Text: "Yeah, you're getting it! Now run along kiddo, that next guy seems a little impatient...",
      Background: "Table",
      Destination: 14,
    },
    {
      Index: 14,
      CharacterState: "SylviaNeut",
      Text: "Welcome welcome, one and all, to the tablke of Sylvia Besk, CEO of Nile Technologies! Now come on, hurry it up, I haven't got all day.",
      Background: "Table",
      Destination: 15,
    },
    {
      Index: 15,
      CharacterState: "SylviaAgit",
      Text: "You know, you're lucky I'm even still here. This is the future of tech, and you think it's acceptable to show up 5 minutes before closing?",
      Background: "Table",
      Destination: 16,
    },
    {
      Index: 16,
      CharacterState: "SylviaNeut",
      Text: "Well whatever. You still came, so you're willing to work. Take this and go already, I'm starving here. ",
      Background: "Table",
      Destination: 17,
    },
    {
      Index: 17,
      CharacterState: "Empty",
      Text: "That was definitely an experience... it looks like all of these cards have times for other meetings on the back. I wonder if I can fit those into my schedule?",
      Background: "Conference",
      Destination: 18,
    },
    {
      Index: 18,
      CharacterState: "Empty",
      Text: "Honestly though with how underqualified they made me out to be, maybe I should take some time to grind first. I'll just head home for the day.",
      Background: "Conference",
      Destination: -1,
    },
    {
      Index: 19,
      CharacterState: "Empty",
      Text: "Oh no! This is a dead end. Maybe the other way instead?",
      Background: "Corridor",
      Destination: 0,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "Empty",
      Text: "Oh Jesus Christ, oh God, oh man. Why do I suddenly feel so tired? My body refuses to move. What is this?",
      Background: "Room",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "Empty",
      Text: "Wait, that's right! I did so much last week... maybe too much. I'm feeling faint...",
      Background: "Room",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "Empty",
      Text: "You find yourself passing out onto the nearest soft object. You do not wake up for the next 2 days.",
      Background: "Room",
      Destination: -1,
    },
  ],
];

const Edna = [
  [
    {
      Index: 0,
      CharacterState: "EdnaNeut",
      Text: "Hello. I see that you came on time. Please, take a seat.",
      Background: "Meeting",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "EdnaNeut",
      Text: "So first, the good news. You have not been rejected.",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "Hooray?", Destination: 2, AffectionChange: 0.0 },
        { OptionIndex: 1.0, Text: "Noted.", Destination: 2, AffectionChange: 1.0 },
      ],
    },
    {
      Index: 2,
      CharacterState: "EdnaNeut",
      Text: "Indeed. But do not celebrate just yet.",
      Background: "Meeting",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "EdnaHappy",
      Text: "We project that your growth through the near future may place you as a potential candidate for one of our lab positions.",
      Background: "Meeting",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "EdnaNeut",
      Text: "This is, however, in no way a guarantee of your success. Before we progress any further, you must first answer some questions for us.",
      Background: "Meeting",
      Destination: 5,
    },
    {
      Index: 5,
      CharacterState: "EdnaNeut",
      Text: "First: How many hours are you willing to commit to the project per week?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 2.0, Text: "Two hundred.", Destination: 6, AffectionChange: -1.0 },
        { OptionIndex: 3.0, Text: "Around ten?", Destination: 7, AffectionChange: -1.0 },
        { OptionIndex: 4.0, Text: "As many as it takes!", Destination: 8, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 6,
      CharacterState: "EdnaNeut",
      Text: "While I admire your dedication, I doubt your physical ability to follow through. After all, there are only 4 days in a week.",
      Background: "Meeting",
      Destination: 9,
    },
    {
      Index: 7,
      CharacterState: "EdnaSad",
      Text: "Unfortunate.",
      Background: "Meeting",
      Destination: 9,
    },
    {
      Index: 8,
      CharacterState: "EdnaShook",
      Text: "An optimal response. I do hope you grasp the full meaning of your words.",
      Background: "Meeting",
      Destination: 9,
    },
    {
      Index: 9,
      CharacterState: "EdnaNeut",
      Text: "Second: Why choose academia? Surely the other options are cushier with the pay. What draws you to science?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 5.0,
          Text: "The hot researchers, of course!",
          Destination: 11,
          AffectionChange: 1.0,
        },
        {
          OptionIndex: 6.0,
          Text: "Uncovering the deep mysteries of nature gives me a special feeling of wonder.",
          Destination: 10,
          AffectionChange: 2.0,
        },
      ],
    },
    {
      Index: 10,
      CharacterState: "EdnaHappy",
      Text: "Ah, a kindred spirit. ",
      Background: "Meeting",
      Destination: 12,
    },
    {
      Index: 11,
      CharacterState: "EdnaShook",
      Text: "Surely there must be a better time for this...",
      Background: "Meeting",
      Destination: 12,
    },
    {
      Index: 12,
      CharacterState: "EdnaNeut",
      Text: "Final question: Why computer science?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 7.0,
          Text: "To help the people I love",
          Destination: 13,
          AffectionChange: 0.0,
        },
        { OptionIndex: 8.0, Text: "Because it's fun!", Destination: 13, AffectionChange: 1.0 },
        {
          OptionIndex: 9.0,
          Text: "Because it can be made better.",
          Destination: 13,
          AffectionChange: 1.0,
        },
      ],
    },
    {
      Index: 13,
      CharacterState: "EdnaNeut",
      Text: "A very interesting set of responses. We may report back after our analysis. Until then, continue to grow.",
      Background: "Meeting",
      Destination: 14,
    },
    {
      Index: 14,
      CharacterState: "EdnaFlus",
      Text: "Thank you for coming to this meeting. It was not unpleasant.",
      Background: "Meeting",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "EdnaNeut",
      Text: "Welcome. Please, take a seat.",
      Background: "Meeting",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "EdnaNeut",
      Text: "You may be aware of the lengths my department goes to in assessing potential candidates for this job. We have been watching you closely.",
      Background: "Meeting",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "EdnaHappy",
      Text: "Congratulations. Weclome to the team! ",
      Background: "Celebration",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "Woah!", Destination: 3, AffectionChange: 0.0 },
        { OptionIndex: 1.0, Text: "Thank you so much! :3", Destination: 3, AffectionChange: 1.0 },
        { OptionIndex: 2.0, Text: "Totally sweet!", Destination: 3, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 3,
      CharacterState: "EdnaNeut",
      Text: "Of course, you'll still have to finish all of our lab trainings and certifications before you're officially on board...",
      Background: "Celebration",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "EdnaNeut",
      Text: "but you're still welcome to visit the lab any time until then.",
      Background: "Celebration",
      Destination: -1,
      Options: [
        {
          OptionIndex: 3.0,
          Text: "Maybe I'll swing by for some coffee later...",
          Destination: 5,
          AffectionChange: 0.0,
        },
        {
          OptionIndex: 4.0,
          Text: "I'd never pass up a chance to see more of you! <3",
          Destination: 6,
          AffectionChange: 1.0,
        },
      ],
    },
    {
      Index: 5,
      CharacterState: "EdnaNeut",
      Text: "You may return home now. I look forwards to working with you!",
      Background: "Celebration",
      Destination: -1,
    },
    {
      Index: 6,
      CharacterState: "EdnaFlus",
      Text: "I'll have you know that's highly unprofessional of you to say! Although I can't say I'm too bothered by the idea...",
      Background: "Celebration",
      Destination: 5,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "EdnaNeut",
      Text: "Welcome. Please, take a seat.",
      Background: "Meeting",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "EdnaNeut",
      Text: "You may be aware of the lengths my department goes to in assessing potential candidates for this job. We have been watching you closely.",
      Background: "Meeting",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "EdnaSad",
      Text: "Unfortunately, we do not believe you are qualified for this position.",
      Background: "Failure",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "...", Destination: 3, AffectionChange: 0.0 },
        { OptionIndex: 1.0, Text: "*sobs*", Destination: 3, AffectionChange: 0.0 },
        { OptionIndex: 2.0, Text: "Noted.", Destination: 3, AffectionChange: 1.0 },
      ],
    },
    {
      Index: 3,
      CharacterState: "EdnaSad",
      Text: "Please note. This is not personal. You simply just lack the necessary expertise.",
      Background: "Failure",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "EdnaNeut",
      Text: "You are always welcome to reapply next year. Best of luck to you.",
      Background: "Failure",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "nan",
      Text: "PLACEHOLDER - DATE",
      Background: "nan",
      Destination: -1,
    },
  ],
];

const Sylvia = [
  [
    {
      Index: 0,
      CharacterState: "SylviaNeut",
      Text: "Welcome. I'm surprised you actually showed up on time for once. Take a seat.",
      Background: "Meeting",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "SylviaAgit",
      Text: "Let's cut the chit chat. We both know why you're here. Buckle up, idiot.",
      Background: "Meeting",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "SylviaNeut",
      Text: "First question.",
      Background: "Meeting",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "SylviaNeut",
      Text: "What are is favorite technology brand?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "Bapple", Destination: 4, AffectionChange: -2.0 },
        { OptionIndex: 1.0, Text: "Bandroid", Destination: 4, AffectionChange: -2.0 },
        {
          OptionIndex: 2.0,
          Text: "Nile Technologies because the precise and refined combination of top notch hardware and software perfectly suits my fancy!",
          Destination: 5,
          AffectionChange: 0.0,
        },
      ],
    },
    {
      Index: 4,
      CharacterState: "SylviaAgit",
      Text: "Tsk. My rivals may have ... a few commendable qualities, but I must say your judgement is questionable!",
      Background: "Meeting",
      Destination: 6,
    },
    {
      Index: 5,
      CharacterState: "SylviaFlus",
      Text: "Indeed, my company is one of many great capabilities. It's what we pride ourselves on here at Nile. ",
      Background: "Meeting",
      Destination: 6,
    },
    {
      Index: 6,
      CharacterState: "SylviaNeut",
      Text: "Now, tell me about your experience in the industry. Let's see what you've got to offer.",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 3.0,
          Text: "I'm just a tech enthusiast who's passionate about Nile Technologies! I've collected ever model of computer you've released eheh!",
          Destination: 7,
          AffectionChange: 2.0,
        },
        {
          OptionIndex: 4.0,
          Text: "I'm a computer science student from one of the best schools in the world.",
          Destination: 8,
          AffectionChange: 0.0,
        },
        {
          OptionIndex: 5.0,
          Text: "I haven't had any experience yet, but just you wait and see! I'll be the best!",
          Destination: 9,
          AffectionChange: -1.0,
        },
      ],
    },
    {
      Index: 7,
      CharacterState: "SylviaFlus",
      Text: "Really now? I'm impressed that someone as lowly as you can even afford them.",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 6.0,
          Text: "I sold everything I had to buy the Papyrus 84 RGB edition!",
          Destination: 10,
          AffectionChange: 1.0,
        },
      ],
    },
    {
      Index: 8,
      CharacterState: "SylviaNeut",
      Text: "Eh, whatever. You're all the same. A dime a dozen.",
      Background: "Meeting",
      Destination: 11,
    },
    {
      Index: 9,
      CharacterState: "SylviaTsun",
      Text: "We'll see about that.",
      Background: "Meeting",
      Destination: 11,
    },
    {
      Index: 10,
      CharacterState: "SylviaNeut",
      Text: "Hmph. You're a bold one. I can't imagine what gives you that confidence.",
      Background: "Meeting",
      Destination: 11,
    },
    {
      Index: 11,
      CharacterState: "SylviaNeut",
      Text: "Anyways, final question.",
      Background: "Meeting",
      Destination: 12,
    },
    {
      Index: 12,
      CharacterState: "SylviaNeut",
      Text: "Why are you even trying? To be a computer scientist, I mean. What made you even consider it?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 7.0, Text: "The money.", Destination: 13, AffectionChange: 0.0 },
        { OptionIndex: 8.0, Text: "To help other people!", Destination: 13, AffectionChange: 0.0 },
        {
          OptionIndex: 9.0,
          Text: "Because computers can always be improved.",
          Destination: 14,
          AffectionChange: 1.0,
        },
      ],
    },
    {
      Index: 13,
      CharacterState: "SylviaNeut",
      Text: "That's the end. Thanks for keeping it short. Who knows, maybe if you keep being this stubborn you might actually see me again.",
      Background: "Meeting",
      Destination: -1,
    },
    {
      Index: 14,
      CharacterState: "SylviaFlus",
      Text: "Is that so? You might just be worth something after all.",
      Background: "Meeting",
      Destination: 13,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "SylviaNeut",
      Text: "I see you're also at this years Big Tech Convention. ",
      Background: "Table",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "SylviaNeut",
      Text: "If you're really so desperate to join Nile, let's have you help me out- err",
      Background: "Table",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "SylviaFlus",
      Text: "Not that I need help or anything!",
      Background: "Table",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "SylviaAgit",
      Text: "But I guess you could consider it a chance for you to prove your skills to me - that's all!",
      Background: "Table",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "SylviaNeut",
      Text: "My tech guy is in the bathroom right now, but maybe something in that pea brain of yours could be of use. It'll be unpaid, of course. ",
      Background: "Table",
      Destination: 5,
    },
    {
      Index: 5,
      CharacterState: "SylviaTsun",
      Text: "what's the difference between HTML and CSS?",
      Background: "Table",
      Destination: -1,
      Options: [
        {
          OptionIndex: 10.0,
          Text: "css is used for the actual content of a web page, but html is concerned with the stylization and design aspect!",
          Destination: 7,
          AffectionChange: -1.0,
        },
        { OptionIndex: 11.0, Text: "um er uhhhhhhh SOB", Destination: 8, AffectionChange: -2.0 },
        {
          OptionIndex: 12.0,
          Text: "html is used for the actual content of a web page, but css is concerned with the stylization and design aspect!",
          Destination: 6,
          AffectionChange: 1.0,
        },
      ],
    },
    {
      Index: 6,
      CharacterState: "SylviaFlus",
      Text: "Is that right? Thanks I guess.",
      Background: "Table",
      Destination: 9,
    },
    {
      Index: 7,
      CharacterState: "SylviaNeut",
      Text: "That doesnt sound right. ",
      Background: "Table",
      Destination: 9,
    },
    {
      Index: 8,
      CharacterState: "SylviaAgit",
      Text: "Incompetent fool! ",
      Background: "Table",
      Destination: 9,
    },
    {
      Index: 9,
      CharacterState: "SylviaNeut",
      Text: "next question: what computer program do people use to write code?",
      Background: "Table",
      Destination: -1,
      Options: [
        {
          OptionIndex: 13.0,
          Text: "some people use python, java, etc.",
          Destination: 11,
          AffectionChange: 2.0,
        },
        { OptionIndex: 14.0, Text: "what is a code?", Destination: 10, AffectionChange: -2.0 },
      ],
    },
    {
      Index: 10,
      CharacterState: "SylviaAgit",
      Text: "You have got to be kidding me! ",
      Background: "Table",
      Destination: 12,
    },
    {
      Index: 11,
      CharacterState: "SylviaNeut",
      Text: "Hmph. A satisfactory answer.",
      Background: "Table",
      Destination: 12,
    },
    {
      Index: 12,
      CharacterState: "SylviaNeut",
      Text: "Alright that's it. Maybe I'll see you around some time.",
      Background: "Table",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "nan",
      Text: "PLACEHOLDER - SUCCESS",
      Background: "nan",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "nan",
      Text: "PLACEHOLDER - FAILURE",
      Background: "nan",
      Destination: -1,
    },
  ],
];

const Martin = [
  [
    {
      Index: 0,
      CharacterState: "MartinRizz",
      Text: "Hey! So nice to see you again! How's it been?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "Terrible! ", Destination: 2, AffectionChange: -1 },
        {
          OptionIndex: 1.0,
          Text: "It's great to see you too!",
          Destination: 1,
          AffectionChange: 0,
        },
        { OptionIndex: 2.0, Text: "It's been swell.", Destination: 1, AffectionChange: 1 },
      ],
    },
    {
      Index: 1,
      CharacterState: "MartinNeut",
      Text: "That's great to hear! Greetings aside though, it's time to get into the meat and potatoes of this meeting.",
      Background: "Meeting",
      Destination: 3,
    },
    {
      Index: 2,
      CharacterState: "MartinGloom",
      Text: "That's unfortunate. I wish I had time to mourn your loss, but unfortunately we have other topics to discuss.",
      Background: "Meeting",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "MartinNeut",
      Text: "Let's get down to business. Our company has a few openings, but they're nothing official.",
      Background: "Meeting",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "MartinRizz",
      Text: 'You\'re under consideration but we need to see a bit... "more" before we can make a decision. ',
      Background: "Meeting",
      Destination: 5,
    },
    {
      Index: 5,
      CharacterState: "MartinRizz",
      Text: "We're going to start off with a few questions. First off: What do you find most fulfilling in life?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 3.0,
          Text: "Defending my nation at any and all costs!",
          Destination: 6,
          AffectionChange: 1,
        },
        {
          OptionIndex: 4.0,
          Text: "Churning out software faster than ChatGPT!",
          Destination: 6,
          AffectionChange: 1,
        },
        { OptionIndex: 5.0, Text: "Talking to you <3", Destination: 7, AffectionChange: 2 },
      ],
    },
    {
      Index: 6,
      CharacterState: "MartinMyst",
      Text: "That's what I like to hear! On to the next question!",
      Background: "Meeting",
      Destination: 8,
    },
    {
      Index: 7,
      CharacterState: "MartinFlus",
      Text: "Oh my~ Maybe some other time- the interview must continue!",
      Background: "Meeting",
      Destination: 8,
    },
    {
      Index: 8,
      CharacterState: "MartinNeut",
      Text: "Where do you see yourself in 5 years?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 6.0, Text: "At your mom's house", Destination: 9, AffectionChange: -2 },
        {
          OptionIndex: 7.0,
          Text: "A succesful SWE at Raylock, climbing the corporate ladder",
          Destination: 10,
          AffectionChange: 0,
        },
        {
          OptionIndex: 8.0,
          Text: "Working at another company, probably",
          Destination: 9,
          AffectionChange: -1,
        },
      ],
    },
    {
      Index: 9,
      CharacterState: "MartinGloom",
      Text: "Well that's rather rude of you to say...",
      Background: "Meeting",
      Destination: 10,
    },
    {
      Index: 10,
      CharacterState: "MartinNeut",
      Text: "Final question: Why did you get into computer science to start with?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 9.0, Text: "For the money", Destination: 11, AffectionChange: -1 },
        {
          OptionIndex: 10.0,
          Text: "To help out the people I love",
          Destination: 12,
          AffectionChange: 1,
        },
        { OptionIndex: 11.0, Text: "Because it's fun!", Destination: 11, AffectionChange: 0 },
      ],
    },
    {
      Index: 11,
      CharacterState: "MartinNeut",
      Text: "That's it for now! Thanks for coming out today. If you keep doing this well, expect more from us soon!",
      Background: "Meeting",
      Destination: -1,
    },
    {
      Index: 12,
      CharacterState: "MartinIbuk",
      Text: "What a noble goal!",
      Background: "Meeting",
      Destination: 11,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "MartinNeut",
      Text: "Hey there! Welcome back to the meeting room. I've got some really important news for you...",
      Background: "Meeting",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "MartinMyst",
      Text: "After a lot of discussion with my superiors and internal review, we've decided... ",
      Background: "Meeting",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "MartinRizz",
      Text: "to offer you a job!",
      Background: "Celebration",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "Wow!", Destination: 3, AffectionChange: 0 },
        { OptionIndex: 1.0, Text: "Thank you so much! <3", Destination: 3, AffectionChange: 1 },
        { OptionIndex: 2.0, Text: "Totally sweet!", Destination: 3, AffectionChange: 0 },
      ],
    },
    {
      Index: 3,
      CharacterState: "MartinFlus",
      Text: "Personally, I'm looking forwards to seeing more of you around... ",
      Background: "Celebration",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "MartinNeut",
      Text: "Anyways.",
      Background: "Celebration",
      Destination: 5,
    },
    {
      Index: 5,
      CharacterState: "MartinNeut",
      Text: "We're ready to let you start by the end of the week, once you finish with the paperwork security clearance and whatnot, ",
      Background: "Celebration",
      Destination: 6,
    },
    {
      Index: 6,
      CharacterState: "MartinNeut",
      Text: "But congratulations! You did it! You're free to go home, but don't forget to collect your complimentary Raylock Employee Mini-RPG on the way out!",
      Background: "Celebration",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "MartinNeut",
      Text: "Hey there! Welcome back to the meeting room. I've got some really important news for you...",
      Background: "Meeting",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "MartinMyst",
      Text: "After a lot of discussion with my superiors and internal review, we've decided... ",
      Background: "Meeting",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "MartinGloom",
      Text: "Not to take you.",
      Background: "Failure",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "...", Destination: 3, AffectionChange: 0 },
        { OptionIndex: 1.0, Text: "*sobs*", Destination: 3, AffectionChange: 0 },
        { OptionIndex: 2.0, Text: "I understand...", Destination: 3, AffectionChange: 1 },
      ],
    },
    {
      Index: 3,
      CharacterState: "MartinRizz",
      Text: "Now don't get me wrong. Personally, I'd love to have you on the team.",
      Background: "Failure",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "MartinGloom",
      Text: "But it's just not going to work out. Maybe in another timeline.",
      Background: "Failure",
      Destination: 5,
    },
    {
      Index: 5,
      CharacterState: "MartinGloom",
      Text: "You should head home now. Feel free to take a Raylock Rejection Mini Nerf Gun with you though.",
      Background: "Failure",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "MartinRizz",
      Text: "Hey there! Glad you make it! We were just about to head out to the field, come on!",
      Background: "Conference",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "Empty",
      Text: "You hop in a consipicuously marked Raylock van. It smells like gunpowder inside.",
      Background: "Black",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "Empty",
      Text: "It's a bumpy ride. But you're glad Martin is there with you",
      Background: "Black",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "MartinRizz",
      Text: "Hey, ya doing ok? You looked a bit queasy in the car.",
      Background: "Field",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "Yeah, I'm fine! *hurk*", Destination: 4, AffectionChange: -1 },
        {
          OptionIndex: 1.0,
          Text: "I'm doing alright, thanks for noticing.",
          Destination: 6,
          AffectionChange: 1,
        },
        { OptionIndex: 2.0, Text: "Send help...", Destination: 4, AffectionChange: 0 },
      ],
    },
    {
      Index: 4,
      CharacterState: "MartinGloom",
      Text: "Hold on, let me get some water for you.",
      Background: "Field",
      Destination: 5,
    },
    {
      Index: 5,
      CharacterState: "Empty",
      Text: "You feel refreshed after drinking the water.",
      Background: "Field",
      Destination: 6,
    },
    {
      Index: 6,
      CharacterState: "MartinNeut",
      Text: "Hopefully the show'll clear that up a bit.",
      Background: "Field",
      Destination: 7,
    },
    {
      Index: 7,
      CharacterState: "MartinRizz",
      Text: "Anyways welcome to the air show! A lot of the planes you'll see today are actually Raylock products. Pretty cool, right?",
      Background: "Field",
      Destination: 8,
    },
    {
      Index: 8,
      CharacterState: "MartinIbuk",
      Text: "My dad actually used to take me to these all the time. It's how I got into the industry in the first place!",
      Background: "Field",
      Destination: 9,
    },
    {
      Index: 9,
      CharacterState: "MartinNeut",
      Text: "It's been a bit of a tradition lately for the company to show off a bit to candidates we're considering strongly. I gotta say, I'm a bit jealous.",
      Background: "Field",
      Destination: 10,
    },
    {
      Index: 10,
      CharacterState: "MartinRizz",
      Text: "What do you think of this one here? Newest model, RL-52 Strategic Bomber. One of these babies cost the military 2 billion!",
      Background: "Field",
      Destination: -1,
      Options: [
        { OptionIndex: 3.0, Text: "Looks cool!", Destination: 12, AffectionChange: 1 },
        { OptionIndex: 4.0, Text: "Looks dangerous...", Destination: 12, AffectionChange: -1 },
        {
          OptionIndex: 5.0,
          Text: "How much does it cost the company though?",
          Destination: 11,
          AffectionChange: 1,
        },
      ],
    },
    {
      Index: 11,
      CharacterState: "MartinMyst",
      Text: "Ah, well that's a bit of a trade secret. You'll find out if you join the company, but no spoilers!",
      Background: "Field",
      Destination: 12,
    },
    {
      Index: 12,
      CharacterState: "MartinNeut",
      Text: "You know, we also have other products. Smaller stuff; toys, grenades, drills and stuff. You'll probably see some of it if you're paying attention today.",
      Background: "Field",
      Destination: 13,
    },
    {
      Index: 13,
      CharacterState: "MartinNeut ",
      Text: "Oh woah! Look at that one over there!",
      Background: "Field",
      Destination: 14,
    },
    {
      Index: 14,
      CharacterState: "Empty",
      Text: "You find yourself alone as Martin wanders over to a shiny-looking airplane.",
      Background: "Field",
      Destination: -1,
      Options: [
        { OptionIndex: 6.0, Text: "Follow Martin", Destination: 15, AffectionChange: 5 },
        { OptionIndex: 7.0, Text: "Stay in place", Destination: 17, AffectionChange: 3 },
      ],
    },
    {
      Index: 15,
      CharacterState: "MartinFlus",
      Text: "Oh hey! Sorry for losing you back there- I kind of lost track of time. My bad.",
      Background: "Field",
      Destination: -1,
    },
    {
      Index: 16,
      CharacterState: "MartinNeut",
      Text: "Speaking of, the big show's about to start! It might get a bit loud thou-",
      Background: "Field",
      Destination: -1,
    },
    {
      Index: 17,
      CharacterState: "Empty",
      Text: "You look at another plane. This one has a plaque under it with some photos.",
      Background: "Field",
      Destination: 18,
    },
    {
      Index: 18,
      CharacterState: "Empty",
      Text: '"The RL-42 Dog-Fighter. Made to aerially shoot enemy war dogs with non-lethal water from specially-modified spray bottles."',
      Background: "Field",
      Destination: 19,
    },
    {
      Index: 19,
      CharacterState: "Empty",
      Text: '"Lead designer: Sergeant Martin L. Ray" ????',
      Background: "Field",
      Destination: 20,
    },
    {
      Index: 20,
      CharacterState: "Empty",
      Text: "THOOOOOOOM",
      Background: "Plane",
      Destination: 21,
    },
    {
      Index: 21,
      CharacterState: "MartinMyst",
      Text: "Woah hoah, ho! What a boom! That kind of stuff never gets old.",
      Background: "Field",
      Destination: 22,
    },
    {
      Index: 22,
      CharacterState: "MartinRizz",
      Text: "So what'd you think? Show's pretty much over at this point.",
      Background: "Field",
      Destination: -1,
      Options: [
        {
          OptionIndex: 8.0,
          Text: "I think I want to go home now...",
          Destination: 23,
          AffectionChange: -1,
        },
        { OptionIndex: 9.0, Text: "That was awesome! ", Destination: 23, AffectionChange: 2 },
        {
          OptionIndex: 10.0,
          Text: "I definitely learned a lot about Raylock. ",
          Destination: 23,
          AffectionChange: 1,
        },
      ],
    },
    {
      Index: 23,
      CharacterState: "MartinFlus",
      Text: "Well I'm glad you came out today! Hope you had fun!",
      Background: "Field",
      Destination: 24,
    },
    {
      Index: 24,
      CharacterState: "Empty",
      Text: "The drive back is just as bumpy, but feels more relaxing somehow.",
      Background: "Black",
      Destination: -1,
    },
  ],
];

const Jp = [
  [
    {
      Index: 0,
      CharacterState: "JpRizz",
      Text: "Hey kiddo, welcome to the meeting! Let's get right into it.",
      Background: "Meeting",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "JpRizz",
      Text: "Look. I'm a businessman, I do business. But what I really need to know, is...",
      Background: "Meeting",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "JpTrade",
      Text: "are YOU a businessman?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "Yes.", Destination: 3, AffectionChange: 1.0 },
        { OptionIndex: 1.0, Text: "No.", Destination: 4, AffectionChange: -10.0 },
        { OptionIndex: 2.0, Text: "Business.", Destination: 5, AffectionChange: 2.0 },
      ],
    },
    {
      Index: 3,
      CharacterState: "JpNeut",
      Text: "Interesting. Let's see you prove it.",
      Background: "Meeting",
      Destination: 6,
    },
    {
      Index: 4,
      CharacterState: "JpAgit",
      Text: "Get out of my sight.",
      Background: "Meeting",
      Destination: -1,
    },
    {
      Index: 5,
      CharacterState: "JpRizz",
      Text: "Ah yes, a fellow man of business. We love to see it.",
      Background: "Meeting",
      Destination: 6,
    },
    {
      Index: 6,
      CharacterState: "JpNeut",
      Text: "Anwyays. We're gonna ask you a few questions to get a read on your business vibe.",
      Background: "Meeting",
      Destination: 7,
    },
    { Index: 7, CharacterState: "JpRizz", Text: "First.", Background: "Meeting", Destination: 8 },
    {
      Index: 8,
      CharacterState: "JpNeut",
      Text: "What is the most important number that you value in a partner?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 3.0, Text: "Body count", Destination: 9, AffectionChange: 0.0 },
        { OptionIndex: 4.0, Text: "Net worth", Destination: 10, AffectionChange: 2.0 },
        { OptionIndex: 5.0, Text: "Follicle count", Destination: 9, AffectionChange: -1.0 },
      ],
    },
    {
      Index: 9,
      CharacterState: "JpAgit",
      Text: "These are definitely some of the numbers ever.",
      Background: "Meeting",
      Destination: 11,
    },
    {
      Index: 10,
      CharacterState: "JpRizz",
      Text: "Extremely true of you.",
      Background: "Meeting",
      Destination: 11,
    },
    {
      Index: 11,
      CharacterState: "JpNeut",
      Text: "Second question.",
      Background: "Meeting",
      Destination: 12,
    },
    {
      Index: 12,
      CharacterState: "JpNeut",
      Text: "How much do you value money?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 6.0, Text: "More than my own life.", Destination: 13, AffectionChange: 2.0 },
        { OptionIndex: 7.0, Text: "It's just ok.", Destination: 14, AffectionChange: -1.0 },
        { OptionIndex: 8.0, Text: "The world runs on it.", Destination: 14, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 13,
      CharacterState: "JpRizz",
      Text: "As you should.",
      Background: "Meeting",
      Destination: 15,
    },
    {
      Index: 14,
      CharacterState: "JpNeut",
      Text: "That's alright. Other things do definitely exist.",
      Background: "Meeting",
      Destination: 15,
    },
    {
      Index: 15,
      CharacterState: "JpTrade",
      Text: "Final question: Why Computer Science? Why, in fact, choose anythign but business?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 9.0,
          Text: "Because it can be imrpoved.",
          Destination: 16,
          AffectionChange: -1.0,
        },
        { OptionIndex: 10.0, Text: "For the money.", Destination: 16, AffectionChange: 2.0 },
        { OptionIndex: 11.0, Text: "Because it's fun.", Destination: 16, AffectionChange: -1.0 },
      ],
    },
    {
      Index: 16,
      CharacterState: "JpNeut",
      Text: "Interesting response.",
      Background: "Meeting",
      Destination: 17,
    },
    {
      Index: 17,
      CharacterState: "JpNeut",
      Text: "Well thank you for coming out today. If you continue to dedicate yourself to business, we may meet again.",
      Background: "Meeting",
      Destination: 18,
    },
    {
      Index: 18,
      CharacterState: "JpRizz",
      Text: "And remember. Avarice is Awesome.",
      Background: "Meeting",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "JpNeut",
      Text: "Hello my friend, have you heard of the annual business competition hosted by the Ungulate Institute of Technology (UIT)?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "Yes.", Destination: 1, AffectionChange: 0.0 },
        { OptionIndex: 1.0, Text: "No.", Destination: 2, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 1,
      CharacterState: "JpNeut",
      Text: "As expected, you are on top of things. So I assume you intend to compete.",
      Background: "Meeting",
      Destination: 6,
    },
    {
      Index: 2,
      CharacterState: "JpNeut",
      Text: "Oho? Deadlines fast approach. Let me give you the rundown.",
      Background: "Meeting",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "JpNeut",
      Text: "Each year, UIT hosts a prestigious competition where the SHARPEST of businessmen compete to DO BUSINESS. Needless to say, it is a serious affair.",
      Background: "Meeting",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "JpNeut",
      Text: "Businesspeople like us must put in our fullest efforts to climb to the top!",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 2.0,
          Text: "There's no way I'd rather spend my time!",
          Destination: 6,
          AffectionChange: 1.0,
        },
        {
          OptionIndex: 3.0,
          Text: "Sounds like a job for me - count me in!",
          Destination: 6,
          AffectionChange: 1.0,
        },
        {
          OptionIndex: 4.0,
          Text: "I'm busy, I don't have time for this.",
          Destination: 5,
          AffectionChange: 0.0,
        },
      ],
    },
    {
      Index: 5,
      CharacterState: "JpNeut",
      Text: "It can't be helped. Perhaps next year then.",
      Background: "Meeting",
      Destination: -1,
    },
    {
      Index: 6,
      CharacterState: "JpRizz",
      Text: "That's what I like to hear!",
      Background: "Meeting",
      Destination: 7,
    },
    {
      Index: 7,
      CharacterState: "JpNeut",
      Text: "This year's theme is an interesting one. They're looking for a business proposal inspired by \"U & I\". ",
      Background: "Meeting",
      Destination: 8,
    },
    {
      Index: 8,
      CharacterState: "JpNeut",
      Text: "I want to hear your thoughts. Maybe I could give you some pointers, as an expert in the trade, hohoho.",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 5.0,
          Text: "I propose a dating sim. ",
          Destination: 9,
          AffectionChange: 0.0,
        },
        {
          OptionIndex: 6.0,
          Text: 'A food truck, but all the ingredients start with "u" or "i".',
          Destination: -1,
          AffectionChange: 0.0,
        },
        {
          OptionIndex: 7.0,
          Text: 'An environmentally destructive crypto start up that sells nfts of "U&I" in different fonts!',
          Destination: -1,
          AffectionChange: 0.0,
        },
      ],
    },
    {
      Index: 9,
      CharacterState: "JpNeut",
      Text: "Curious! It's an intriguing idea... I like it!",
      Background: "Meeting",
      Destination: 10,
    },
    {
      Index: 10,
      CharacterState: "JpTrade",
      Text: "So hear me out, what if you did that, but with me, JP SILVERBAGS as the lead love interest?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 8.0,
          Text: "Thanks for the feedback JP.",
          Destination: 12,
          AffectionChange: 0.0,
        },
        {
          OptionIndex: 9.0,
          Text: "You're already the lead love interest in my life~",
          Destination: 11,
          AffectionChange: 3.0,
        },
        { OptionIndex: 10.0, Text: "S-sure //uwu//", Destination: 13, AffectionChange: 1.0 },
      ],
    },
    {
      Index: 11,
      CharacterState: "JpRizz",
      Text: "Ohoho! You've got the charisma of a businessman that's for sure!",
      Background: "Meeting",
      Destination: 20,
    },
    {
      Index: 12,
      CharacterState: "JpNeut",
      Text: "You're a coolheaded business person. ",
      Background: "Meeting",
      Destination: 20,
    },
    {
      Index: 13,
      CharacterState: "JpRizz",
      Text: "I look forward to seeing your creation~",
      Background: "Meeting",
      Destination: 20,
    },
    {
      Index: 14,
      CharacterState: "JpNeut",
      Text: "Crypto! I'm excited. If things go well, you could have a fortune on your hands!",
      Background: "Meeting",
      Destination: 20,
    },
    {
      Index: 15,
      CharacterState: "JpNeut",
      Text: "I'm an enjoyer of food trucks myself, it's a respectable idea.",
      Background: "Meeting",
      Destination: 16,
    },
    {
      Index: 16,
      CharacterState: "JpRizz",
      Text: "If you ever open up a food truck, you'll give me a special discount right?~~",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 11.0, Text: "Deal", Destination: 16, AffectionChange: 1.0 },
        {
          OptionIndex: 12.0,
          Text: "No way, I can't be skimping on the profits!",
          Destination: 17,
          AffectionChange: -1.0,
        },
        { OptionIndex: 13.0, Text: "No deal", Destination: 18, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 17,
      CharacterState: "JpAgit",
      Text: "You are a shrewd businessman. But a stingy one too. There are times to be generous... I suppose you do not believe I am a connection worth your investment.",
      Background: "Meeting",
      Destination: 20,
    },
    {
      Index: 18,
      CharacterState: "JpNeut",
      Text: "Fair enough.",
      Background: "Meeting",
      Destination: 20,
    },
    {
      Index: 19,
      CharacterState: "JpTrade",
      Text: "OHOHO! I'll remember this!",
      Background: "Meeting",
      Destination: 20,
    },
    {
      Index: 20,
      CharacterState: "JpNeut",
      Text: "Next, I want to hear about your progress. How far along are you on the project?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 14.0,
          Text: "Not far.. But I'll put in my 110% tonight!",
          Destination: 21,
          AffectionChange: 1.0,
        },
        {
          OptionIndex: 15.0,
          Text: "I've got the budgeting and logistics all figured out! We're projected to haul in a lofty profit!",
          Destination: 22,
          AffectionChange: 1.0,
        },
        {
          OptionIndex: 16.0,
          Text: "I've thought about it but I have yet to actualize it.",
          Destination: 23,
          AffectionChange: 0.0,
        },
      ],
    },
    {
      Index: 21,
      CharacterState: "JpNeut",
      Text: "Haha, back in the day I was like that too. Don't worry, you can do it! Just give it your best shot. Entrepeneurs can make anything happen.",
      Background: "Meeting",
      Destination: -1,
    },
    {
      Index: 22,
      CharacterState: "JpRizz",
      Text: "That's what I like to hear! I look forward to seeing you, on the podium~",
      Background: "Meeting",
      Destination: -1,
    },
    {
      Index: 23,
      CharacterState: "JpNeut",
      Text: "Well get on it! The clock is ticking...",
      Background: "Meeting",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "JpRizz",
      Text: "Hey Baby~ I've got a story to tell. A lesson if you will...",
      Background: "Meeting",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "JpRizz",
      Text: "Today is the day you may bear witness to a great legend.",
      Background: "Meeting",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "JpNeut",
      Text: "The story of how a great man became bald.",
      Background: "Meeting",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "JpRizz",
      Text: "But what I REALLY need to know is...",
      Background: "Meeting",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "JpTrade",
      Text: "Are YOU ready to hear it?",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 1.0, Text: "YES t=0!", Destination: 6, AffectionChange: 1.0 },
        { OptionIndex: 2.0, Text: "sure", Destination: 6, AffectionChange: 0.0 },
        { OptionIndex: 3.0, Text: "No", Destination: 5, AffectionChange: -1.0 },
      ],
    },
    {
      Index: 5,
      CharacterState: "JpAgit",
      Text: "You don't have a choice",
      Background: "Meeting",
      Destination: 7,
    },
    {
      Index: 6,
      CharacterState: "JpTrade",
      Text: "Hoho... Well then...",
      Background: "Meeting",
      Destination: 7,
    },
    {
      Index: 7,
      CharacterState: "JpNeut",
      Text: "Once upon a time, there was a young man named Jaypee. ",
      Background: "Meeting",
      Destination: 8,
    },
    {
      Index: 8,
      CharacterState: "JpNeut",
      Text: "He had a head full of thick, healthy, glossy hair.",
      Background: "Meeting",
      Destination: 9,
    },
    {
      Index: 9,
      CharacterState: "JpNeut",
      Text: "Then one day, as he was frolicking in the meadows, as one does, enjoying the sunshine of youth...",
      Background: "Meadows",
      Destination: 10,
    },
    {
      Index: 10,
      CharacterState: "JpNeut",
      Text: "He had a premonition.",
      Background: "Meadows",
      Destination: 11,
    },
    {
      Index: 11,
      CharacterState: "JpRizz",
      Text: "In his vision, a wise suited man descended from the heavens",
      Background: "Meadows",
      Destination: 12,
    },
    {
      Index: 12,
      CharacterState: "JpTrade",
      Text: "And this man, he made a trade offer.",
      Background: "Meadows",
      Destination: 13,
    },
    {
      Index: 13,
      CharacterState: "JpTrade",
      Text: 'He told me this: "Young lad, trade offer: you receive businessman status for life. I receive your soul." ',
      Background: "Meadows",
      Destination: -1,
      Options: [
        { OptionIndex: 4.0, Text: "What a great offer!", Destination: 14, AffectionChange: 1.0 },
        { OptionIndex: 5.0, Text: "oh.", Destination: 14, AffectionChange: -1.0 },
      ],
    },
    {
      Index: 14,
      CharacterState: "JpNeut",
      Text: "Of course, it was an offer I couldn't pass up. I had been waiting for a trade offer my whole life",
      Background: "Meadows",
      Destination: 15,
    },
    {
      Index: 15,
      CharacterState: "JpRizz",
      Text: "Fourteen years of life on this planet had all been leading up to this. I was salivating!",
      Background: "Meadows",
      Destination: 16,
    },
    {
      Index: 16,
      CharacterState: "JpRizz",
      Text: "I was a charismatic young man, BORN TO DO BUSINESS!!",
      Background: "Meadows",
      Destination: -1,
      Options: [
        { OptionIndex: 6.0, Text: "As you were!", Destination: 17, AffectionChange: 1.0 },
        { OptionIndex: 7.0, Text: "ok.", Destination: 18, AffectionChange: -1.0 },
      ],
    },
    { Index: 17, CharacterState: "nan", Text: "As I was!", Background: "Meadows", Destination: 18 },
    {
      Index: 18,
      CharacterState: "JpNeut",
      Text: "Ahem.. Anyways, I -  uh I mean, Jaypee - was sent into such a state of intense euphoria",
      Background: "Meadows",
      Destination: 19,
    },
    {
      Index: 19,
      CharacterState: "JpAgit",
      Text: "that my follicles loosened and my - I mean, his - hair began to fall out",
      Background: "Meadows",
      Destination: 20,
    },
    {
      Index: 20,
      CharacterState: "JpAgit",
      Text: "For ten days, hair fell out non stop, starting from the left side of Jaypee's scalp, then progressing to the right side. The baldness could not be stopped.",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 8.0, Text: "Oh golly...", Destination: 21, AffectionChange: 0.0 },
        {
          OptionIndex: 9.0,
          Text: "Oh god oh man oh god oh man!",
          Destination: 21,
          AffectionChange: 0.0,
        },
      ],
    },
    {
      Index: 21,
      CharacterState: "JpTrade",
      Text: "But when it came time to found a start up, Jaypee saw what he had to do. He turned the baldness into a business opportunity. ",
      Background: "Meeting",
      Destination: 22,
    },
    {
      Index: 22,
      CharacterState: "JpRizz",
      Text: "As a new entrant into the solar power industry, Jaypee saw the potential in his bald head.",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 10.0, Text: "It's shiny.", Destination: 23, AffectionChange: 2.0 },
        { OptionIndex: 11.0, Text: "I don't quite follow.", Destination: 24, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 23,
      CharacterState: "JpRizz",
      Text: "YES! Precisely!",
      Background: "Sun",
      Destination: 25,
    },
    {
      Index: 24,
      CharacterState: "JpNeut",
      Text: "Don't worry, I'll explain. ",
      Background: "Meeting",
      Destination: 25,
    },
    {
      Index: 25,
      CharacterState: "JpNeut",
      Text: "Jaypee saw that his shiny bald scalp could be used to reflect sunlight, bouncing sunlight back onto solar panels, reducing the waste of potential energy.",
      Background: "Sun",
      Destination: 26,
    },
    {
      Index: 26,
      CharacterState: "JpRizz",
      Text: "Knowing this, he was able to strategically position his bald head, boosting power generation by 200%!",
      Background: "Sun",
      Destination: -1,
      Options: [
        {
          OptionIndex: 12.0,
          Text: "You're a genius! The profits must have been through the roof!",
          Destination: 27,
          AffectionChange: 1.0,
        },
        { OptionIndex: 13.0, Text: "I see. ", Destination: 28, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 27,
      CharacterState: "JpNeut",
      Text: "Right~ Hoho! ",
      Background: "Sun",
      Destination: 29,
    },
    { Index: 28, CharacterState: "JpNeut", Text: "Indeed.", Background: "Sun", Destination: 29 },
    {
      Index: 29,
      CharacterState: "JpRizz",
      Text: "Anyways, I wanted to say: I see you the way I see that scalp. You've got potential.",
      Background: "Sun",
      Destination: -1,
      Options: [
        {
          OptionIndex: 14.0,
          Text: "Let's unlock that potential together. ",
          Destination: 31,
          AffectionChange: 3.0,
        },
        { OptionIndex: 15.0, Text: "I hate scalps", Destination: 30, AffectionChange: -5.0 },
      ],
    },
    {
      Index: 30,
      CharacterState: "JpAgit",
      Text: "How dare you. you missed the metaphor. You know it's not often that I tell people this story right? I have to say I'm disappointed. ",
      Background: "Meeting",
      Destination: -1,
    },
    {
      Index: 31,
      CharacterState: "JpRizz",
      Text: "Thats what I like to hear. I knew you were a good match.",
      Background: "Sun",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "JpRizz",
      Text: "Greetings, child! So we meet again. Was it fate that the ebbing and flowing of the stock markets pushed us together? ",
      Background: "Meeting",
      Destination: 1,
    },
    {
      Index: 1,
      CharacterState: "JpNeut",
      Text: "Haha, I jest.",
      Background: "Meeting",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "JpNeut",
      Text: " I'm here, not by chance, but because I see you as a connection- a valuable connection even.",
      Background: "Meeting",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "JpNeut",
      Text: "Anyways, let's get down to business.",
      Background: "Meeting",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "JpTrade",
      Text: "I came here today to make you an offer.",
      Background: "Meeting",
      Destination: 5,
    },
    {
      Index: 5,
      CharacterState: "JpTrade",
      Text: "A trade deal, if you will.",
      Background: "Meeting",
      Destination: -1,
      Options: [
        { OptionIndex: 0.0, Text: "I'm listening.", Destination: 6, AffectionChange: 0.0 },
        {
          OptionIndex: 1.0,
          Text: "Sounds great! I love deals!",
          Destination: 6,
          AffectionChange: 1.0,
        },
      ],
    },
    {
      Index: 6,
      CharacterState: "JpRizz",
      Text: "I'm interested in deepening our relationship.",
      Background: "Meeting",
      Destination: -1,
      Options: [
        {
          OptionIndex: 2.0,
          Text: "I too wish to network with you!",
          Destination: 8,
          AffectionChange: 1.0,
        },
        {
          OptionIndex: 3.0,
          Text: "The world revolves around connections. ",
          Destination: 7,
          AffectionChange: 1.0,
        },
        { OptionIndex: 4.0, Text: "*blushing* u- uwu???", Destination: 9, AffectionChange: 0.0 },
      ],
    },
    {
      Index: 7,
      CharacterState: "JpNeut",
      Text: "As it does!",
      Background: "Meeting",
      Destination: 10,
    },
    {
      Index: 8,
      CharacterState: "JpNeut",
      Text: "You learn quickly! I'm always happy to see the growth of young business people!",
      Background: "Meeting",
      Destination: 10,
    },
    {
      Index: 9,
      CharacterState: "JpTrade",
      Text: 'What is "uwu"... Is that a new company perhaps? I\'m interested to see what opportunities it may offer us... I digress',
      Background: "Meeting",
      Destination: 10,
    },
    {
      Index: 10,
      CharacterState: "JpTrade",
      Text: "In any case, congratulations! I've decided you're a great fit for our team here at Silverbags Trading!",
      Background: "Celebration",
      Destination: 11,
    },
    {
      Index: 11,
      CharacterState: "JpRizz",
      Text: "I'm looking forward to seeing you in the office. Building 420, the penthouse. ",
      Background: "Celebration",
      Destination: 12,
    },
    {
      Index: 12,
      CharacterState: "JpRizz",
      Text: "t=0 but u&i=1. I want to invest in you.",
      Background: "Celebration",
      Destination: 13,
    },
    {
      Index: 13,
      CharacterState: "JpRizz",
      Text: "So let's be partners. Business partners.",
      Background: "Celebration",
      Destination: -1,
    },
  ],
  [
    {
      Index: 0,
      CharacterState: "JpNeut",
      Text: "Hello, let's talk. It'll only take a minute of your time.",
      Background: "Corridor",
      Destination: -1,
    },
    { Index: 0, CharacterState: "nan", Text: "Alright", Background: "Corridor", Destination: 1 },
    {
      Index: 1,
      CharacterState: "JpNeut",
      Text: "So let's cut straight to the point:",
      Background: "Meeting",
      Destination: 2,
    },
    {
      Index: 2,
      CharacterState: "JpNeut",
      Text: "You and me, I don't think we'll see eye to eye.",
      Background: "Meeting",
      Destination: 3,
    },
    {
      Index: 3,
      CharacterState: "JpAgit",
      Text: "I don't know if you're cut out for business, much less business at the presitgious Silverbag Trading.",
      Background: "Failure",
      Destination: 4,
    },
    {
      Index: 4,
      CharacterState: "JpNeut",
      Text: "I am formally rejecting you from my company, as much as it pains me - and you. ",
      Background: "Failure",
      Destination: 5,
    },
    {
      Index: 5,
      CharacterState: "JpNeut",
      Text: "But who knows, maybe if you impress me some day. ",
      Background: "Failure",
      Destination: 6,
    },
    {
      Index: 6,
      CharacterState: "JpNeut",
      Text: "I wish you luck with your ventures. Now farewell. I have more profitable matters to be attending to!",
      Background: "Failure",
      Destination: -1,
    },
  ],
];

const ResettiTestySpaghetti = [
  {
    Index: 0,
    CharacterState: "Empty",
    Text: "Hello there! How ya doing?",
    Background: "Room",
    Options: [
      {
        OptionIndex: 0,
        Text: "good",
        AffectionChange: 0,
        Destination: 1,
      },
      {
        OptionIndex: 1,
        Text: "ok",
        AffectionChange: 0,
        Destination: 1,
      },
      {
        OptionIndex: 2,
        Text: "...",
        AffectionChange: -1,
        Destination: 2,
      },
    ],
  },
  {
    Index: 1,
    CharacterState: "myst",
    Text: "Very cool! By the way, do you have a spare moment to talk about our lord and savior, Trevor Johst?",
    Background: "Room",
    Options: [
      {
        OptionIndex: 3,
        Text: "Trevor? I barely know her!",
        AffectionChange: 2,
        Destination: 3,
      },
      {
        OptionIndex: 4,
        Text: "Of course!",
        AffectionChange: 1,
        Destination: 3,
      },
    ],
  },
  {
    Index: 2,
    CharacterState: "gloom",
    Text: "...that bad, huh?",
    Background: "Room",
    Options: [
      {
        OptionIndex: 5,
        Text: "...huh? Oh sorry, I was too busy staring into your eyes...",
        AffectionChange: 4,
        Destination: 1,
      },
    ],
  },
  {
    Index: 3,
    CharacterState: "ibuk",
    Text: "I'm glad to have met a fellow Trevor CONEussier! ",
    Background: "Room",
    Options: [
      {
        OptionIndex: 6,
        Text: "I love cones!",
        AffectionChange: -2,
        Destination: -1,
      },
      {
        OptionIndex: 7,
        Text: "So true!",
        AffectionChange: 1,
        Destination: -1,
      },
    ],
  },
];

const clickthroughTest = [
  {
    Index: 0,
    CharacterState: "rizz",
    Text: "TESTING TESTING, OUT OF THE WAY",
    Background: "Room",
    Destination: 1,
  },
  {
    Index: 1,
    CharacterState: "empty",
    Text: "WOOSH! DISAPPEARED!",
    Background: "Room",
    Destination: -1,
  },
];

export { ResettiTestySpaghetti, clickthroughTest, IntroSegment, Martin, Edna, Sylvia, Jp };
